// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZp6XmH_N0tsyS5oQeGJChl9YmnQ7bUzA',
    appId: '1:418057749611:web:19a541b349091e88ee9d2e',
    messagingSenderId: '418057749611',
    projectId: 'nextsns-39cd7',
    authDomain: 'nextsns-39cd7.firebaseapp.com',
    storageBucket: 'nextsns-39cd7.appspot.com',
    measurementId: 'G-2ENKHL07PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhLQhymU3xCZSJeTzZfhQTiDiQaKjJ1w',
    appId: '1:418057749611:android:2b28ebee45377bd5ee9d2e',
    messagingSenderId: '418057749611',
    projectId: 'nextsns-39cd7',
    storageBucket: 'nextsns-39cd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEc7uBYvbj_ZymvZ7UteSBUPd5k2L2TA',
    appId: '1:418057749611:ios:3bf22c15e6820e2bee9d2e',
    messagingSenderId: '418057749611',
    projectId: 'nextsns-39cd7',
    storageBucket: 'nextsns-39cd7.appspot.com',
    iosClientId: '418057749611-kd11eiopk88lo4vi2ijtnabovjpjdfe1.apps.googleusercontent.com',
    iosBundleId: 'com.quantum-box.discordclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhEc7uBYvbj_ZymvZ7UteSBUPd5k2L2TA',
    appId: '1:418057749611:ios:81676a78d715e81eee9d2e',
    messagingSenderId: '418057749611',
    projectId: 'nextsns-39cd7',
    storageBucket: 'nextsns-39cd7.appspot.com',
    iosClientId: '418057749611-purm4qn3ebrhrd41qc0v2553q3j7eg56.apps.googleusercontent.com',
    iosBundleId: 'com.quantumbox.discordClone',
  );
}
